=== gonicus/gosa/backend/src/gosa/backend/data/object.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--suppress XmlDefaultAttributeValue -->
<schema targetNamespace="http://www.gonicus.de/Objects"
  elementFormDefault="qualified" 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  xmlns:o="http://www.gonicus.de/Objects">

  <complexType name="Object">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Description" type="string" maxOccurs="1" minOccurs="1"/>
      <element name="DisplayName" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="Templates" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Template" type="string" maxOccurs="unbounded" minOccurs="1"/>
          </sequence>
        </complexType>
      </element>
      <element name="Dialogs" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Dialog" type="string" maxOccurs="unbounded" minOccurs="1"/>
          </sequence>
        </complexType>
      </element>
      <element name="BackendParameters" type="o:BackendParameters" maxOccurs="1" minOccurs="0"/>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Attributes" type="o:Attributes" maxOccurs="1" minOccurs="0"/>
      <element name="Container" type="o:ContainerType" maxOccurs="1" minOccurs="0"/>
      <element name="Extends" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"/>
          </sequence>
        </complexType>
      </element>
      <element name="BaseObject" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="Methods" type="o:Methods" maxOccurs="1" minOccurs="0"/>
      <element name="Hooks" type="o:Hooks" maxOccurs="1" minOccurs="0"/>
      <element name="FixedRDN" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="StructuralInvisible" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="RequiresExtension" type="o:RequiresExtension" maxOccurs="1" minOccurs="0"/>
      <element name="ExtensionConditions" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="ExtensionCondition" maxOccurs="unbounded" minOccurs="0">
              <complexType>
                <complexContent>
                  <extension base="o:Validator">
                    <attribute name="extension" type="string" use="required">
                      <annotation>
                        <documentation xml:lang="en">The extension name this condition is related to</documentation>
                      </annotation>
                    </attribute>
                    <attribute name="properties" type="string">
                      <annotation>
                        <documentation xml:lang="en">A list of comma-separated properties that should trigger a
                          re-validation of the condition</documentation>
                      </annotation>
                    </attribute>
                  </extension>
                </complexContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="Find" type="o:Find" maxOccurs="1" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="Attributes">
    <choice maxOccurs="unbounded">
      <element name="ForeignAttribute" type="o:ForeignAttribute" />
      <element name="Attribute" type="o:Attribute" />
    </choice>
  </complexType>

  <complexType name="ForeignAttribute" >
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
    </all>
  </complexType>

  <complexType name="Attribute">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Description" type="string" maxOccurs="1" minOccurs="0">
      </element>
      <element name="DependsOn" type="o:DependsOn" maxOccurs="1" minOccurs="0"/>
      <element name="Backend" type="token" maxOccurs="1" minOccurs="0"/>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"/>
      <element name="Values" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Value" maxOccurs="unbounded" minOccurs="0" type="o:ValueWithKey"/>
          </sequence>
          <attribute name="populate" type="string" use="optional"/>
          <attribute name="refresh-on-update" type="boolean" use="optional"/>
        </complexType>
      </element>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="BackendType" type="o:AttributeBackendTypes" maxOccurs="1" minOccurs="0"/>
      <element name="Validators" type="o:Validator" maxOccurs="1" minOccurs="0"/>
      <element name="InFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"/>
      <element name="OutFilter" type="o:FilterElement" maxOccurs="1" minOccurs="0"/>
      <element name="MultiValue" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="ReadOnly" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="Mandatory" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="Unique" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="Auto" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="BlockedBy" maxOccurs="1" minOccurs="0">
        <complexType>
          <sequence>
            <element name="Attribute" maxOccurs="unbounded" minOccurs="1">
              <complexType>
                <simpleContent>
                  <extension base="string">
                    <attribute name="value" type="string"/>
                  </extension>
                </simpleContent>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
      <element name="CaseSensitive" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="References" type="o:References" maxOccurs="1" minOccurs="0"/>
      <element name="InheritFrom" minOccurs="0" maxOccurs="1">
        <complexType>
          <simpleContent>
            <extension base="string">
              <attribute name="relation" type="string"/>
            </extension>
          </simpleContent>
        </complexType>
      </element>
      <element name="UpdateHooks" minOccurs="0" maxOccurs="1">
        <complexType>
          <sequence>
            <element name="UpdateHook" maxOccurs="unbounded" minOccurs="1">
              <complexType>
                <all>
                  <element name="Object" maxOccurs="1" minOccurs="1"/>
                  <element name="Attribute" maxOccurs="1" minOccurs="1"/>
                </all>
              </complexType>
            </element>
          </sequence>
        </complexType>
      </element>
    </all>
    <!-- python does not support assertions yet: assert test="if (MultiValue = 'true') then not(References/Reference[@mode='inline']) else true()"/-->
  </complexType>

  <simpleType name="AttributeTypes">
    <restriction base="string"/>
  </simpleType>

  <simpleType name="AttributeBackendTypes">
    <restriction base="string">
      <enumeration value="Boolean"/>
      <enumeration value="String"/>
      <enumeration value="UnicodeString"/>
      <enumeration value="Integer"/>
      <enumeration value="Timestamp"/>
      <enumeration value="Date"/>
      <enumeration value="Binary"/>
    </restriction>
  </simpleType>

  <complexType name="ContainerType">
    <sequence>
      <element name="Type" type="token" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <element name="Objects" type="o:Objects"/>

  <complexType name="Objects">
    <sequence>
      <element name="Object" type="o:Object" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Methods">
    <sequence>
      <element name="Method" type="o:Method" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Hooks">
    <sequence>
      <element name="Hook" type="o:Hook" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Method">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="MethodParameters" type="o:MethodParameters" maxOccurs="1" minOccurs="0"/>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"/>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="Hook">
    <all>
      <element name="Type" maxOccurs="1" minOccurs="1">
        <simpleType>
          <restriction base="string">
            <enumeration value="PreCreate"/>
            <enumeration value="PreUpdate"/>
            <enumeration value="PreRemove"/>
            <enumeration value="PostCreate"/>
            <enumeration value="PostUpdate"/>
            <enumeration value="PostRemove"/>
          </restriction>
        </simpleType>
      </element>
      <element name="Command" type="string" maxOccurs="1" minOccurs="1"/>
      <element name="CommandParameters" type="o:CommandParameter" maxOccurs="1" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="Parameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"/>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"/>
    </all>
  </complexType>

  <complexType name="FilterChain">
    <choice>
      <element name="FilterEntry" type="o:FilterEntry" maxOccurs="unbounded" minOccurs="1"/>
    </choice>
  </complexType>

  <complexType name="Choice">
    <sequence>
      <element name="When" type="o:When" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="When">
    <sequence>
      <element name="ConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"/>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"/>
      <element name="Else" type="o:Else" maxOccurs="1" minOccurs="0"/>
    </sequence>

  </complexType>

  <complexType name="ValueWithKey">
    <simpleContent>
      <extension base="string">
        <attribute name="key" type="string"/>
        <attribute name="translate" type="boolean" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="FilterElement">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Filter">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="Else">
    <sequence>
      <element name="FilterChain" type="o:FilterChain" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="ConditionChain">
    <choice>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"/>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"/>
    </choice>
  </complexType>

  <complexType name="Condition">
    <sequence>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Param" type="string" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="Validator">
    <choice>
      <element name="ConditionOperator" type="o:ConditionOperator" maxOccurs="1" minOccurs="0"/>
      <element name="Condition" type="o:Condition" maxOccurs="1" minOccurs="0"/>
    </choice>
  </complexType>

  <complexType name="FilterEntry">
    <choice>
      <element name="Filter" type="o:Filter" maxOccurs="1" minOccurs="0"/>
      <element name="Choice" type="o:Choice" maxOccurs="1" minOccurs="0"/>
    </choice>
  </complexType>

  <complexType name="ConditionOperator">
    <sequence>
      <element name="Operator" type="o:NewType" maxOccurs="1" minOccurs="1"/>
      <element name="LeftConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"/>
      <element name="RightConditionChain" type="o:ConditionChain" maxOccurs="1" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="DependsOn">
    <sequence>
      <element name="Attribute" type="string" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="RequiresExtension">
    <sequence>
      <element name="Extension" type="string" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Find">
    <sequence>
      <element name="Aspect" type="o:Aspect" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Result">
    <sequence>
      <element name="Map" type="o:Map" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

  <complexType name="Map">
    <sequence>
      <element name="Source" type="string" maxOccurs="unbounded" minOccurs="1"/>
      <element name="Destination" type="string" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Aspect">
    <sequence>
      <element name="Tag" type="string" maxOccurs="1" minOccurs="1"/>
      <element name="Keyword" type="string" maxOccurs="unbounded" minOccurs="0"/>
      <element name="Search" type="string" maxOccurs="unbounded" minOccurs="1"/>
      <element name="Resolve" type="o:Resolve" maxOccurs="unbounded" minOccurs="0"/>
      <element name="Result" type="o:Result" maxOccurs="unbounded" minOccurs="0"/>
    </sequence>
  </complexType>

    <complexType name="Resolve">
    <simpleContent>
      <extension base="string">
        <attribute name="filter" type="string"/>
        <attribute name="type" type="string" use="optional"/>
      </extension>
    </simpleContent>
  </complexType>

  <simpleType name="NewType">
    <restriction base="token">
      <enumeration value="or"/>
      <enumeration value="and"/>
    </restriction>
  </simpleType>


  <complexType name="Parameters">
    <sequence>
      <element name="Parameter" type="o:Parameter" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="CommandParameter">
    <sequence>
      <element name="Value" type="string" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>


  <complexType name="MethodParameter">
    <all>
      <element name="Name" type="token" maxOccurs="1" minOccurs="1"/>
      <element name="Required" type="boolean" maxOccurs="1" minOccurs="0"/>
      <element name="Default" type="string" maxOccurs="1" minOccurs="0"/>
      <element name="Type" type="o:AttributeTypes" maxOccurs="1" minOccurs="1"/>
    </all>
  </complexType>

  <complexType name="MethodParameters">
    <sequence>
      <element name="MethodParameter" type="o:MethodParameter" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="BackendParameter">
    <simpleContent>
      <extension base="string">
        <anyAttribute processContents="skip" />
      </extension>
    </simpleContent>
  </complexType>

  <complexType name="BackendParameters">
    <sequence>
      <element name="Backend" type="o:BackendParameter" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="References">
    <sequence>
      <element name="Reference" type="o:Reference" maxOccurs="unbounded" minOccurs="1"/>
    </sequence>
  </complexType>

  <complexType name="Reference">
    <sequence>
      <element name="Object" type="token"/>
      <element name="Attribute" type="token"/>
    </sequence>
    <attribute name="mode" default="replace" use="optional">
      <simpleType>
        <restriction base="string">
          <enumeration value="inline">
            <annotation xml:lang="en">
              <documentation>Replace the reference inside the content string. Note: inline mode does not work in multivalued attributes</documentation>
            </annotation>
          </enumeration>
          <enumeration value="replace">
              <annotation xml:lang="en">
                <documentation>Replace the complete value</documentation>
              </annotation>
          </enumeration>
        </restriction>
      </simpleType>
    </attribute>
    <attribute name="identify-pattern" use="optional">
      <annotation xml:lang="en">
        <documentation>Optional search pattern to identify inline references (might contain ###VALUE### where the old value should be replaced with the new one). This content will be converted via html.unescape and NOT used as a regular expression.</documentation>
      </annotation>
    </attribute>
    <attribute name="replace-pattern" use="optional">
      <annotation xml:lang="en">
        <documentation>Optional search pattern for inline replacement (must contain ###VALUE### where the old value should be replaced with the new one). This content will be converted via html.unescape and used as a regular expression.</documentation>
      </annotation>
    </attribute>
    <attribute name="delete-pattern" use="optional">
      <annotation xml:lang="en">
        <documentation>Optional search pattern for inline deletion of the reference (must contain ###VALUE### where the old value should be replaced with the new one). This content will be converted via html.unescape and used as a regular expression.</documentation>
      </annotation>
    </attribute>
  </complexType>
</schema>

=== gonicus/gosa/backend/src/gosa/backend/data/objects/acl.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>Acl</Name>
    <DisplayName>Acl</DisplayName>
    <Description>Acl extension</Description>
    <BaseObject>false</BaseObject>
    <Backend>JSON</Backend>
    <BackendParameters>
      <Backend type="Acl">JSON</Backend>
    </BackendParameters>
    <Attributes>
      <Attribute>
        <Name>AclSets</Name>
        <Description></Description>
        <Type>AclSet</Type>
        <BackendType>UnicodeString</BackendType>
        <MultiValue>true</MultiValue>
        <Validators>
          <Condition>
            <Name>IsAclSet</Name>
          </Condition>
        </Validators>
      </Attribute>
    </Attributes>
    <Extends>
      <Value>PosixGroup</Value>
      <Value>PeopleContainer</Value>
      <Value>OrganizationalRole</Value>
      <Value>Domain</Value>
      <Value>GroupContainer</Value>
      <Value>DomainComponent</Value>
      <Value>SambaDomain</Value>
      <Value>User</Value>
      <Value>SetBackends</Value>
      <Value>Device</Value>
      <Value>OrganizationalUnit</Value>
      <Value>OrganizationalRoleContainer</Value>
      <Value>Country</Value>
      <Value>Organization</Value>
      <Value>GroupOfNames</Value>
      <Value>Locality</Value>
      <Value>DeviceContainer</Value>
      <Value>DomainComponentOrg</Value>
		</Extends>
	</Object>
</Objects>

=== gonicus/gosa/backend/src/gosa/backend/data/objects/people-container.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>PeopleContainer</Name>
		<DisplayName>Container for users</DisplayName>
		<Description>Organizational unit that can contain users</Description>
		<BackendParameters>
			<Backend objectClasses="organizationalUnit" RDN="ou">LDAP</Backend>
		</BackendParameters>
		<Backend>LDAP</Backend>
		<Container>
			<Type>User</Type>
		</Container>
		<BaseObject>true</BaseObject>
		<FixedRDN>ou=people</FixedRDN>
		<StructuralInvisible>true</StructuralInvisible>
	</Object>
</Objects>

=== gonicus/gosa/backend/src/gosa/data/objects/user-posix.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>PosixUser</Name>
    <DisplayName>POSIX extension</DisplayName>
    <Templates>
      <Template>user-posix.ui</Template>
    </Templates>
    <Description>A posix extension for a generic user</Description>
    <BaseObject>false</BaseObject>
    <BackendParameters>
      <Backend objectClasses="posixAccount">LDAP</Backend>
      <Backend groupMembership="PosixGroup:cn,memberUid=uid">ObjectHandler</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>

    <Attributes>
      <ForeignAttribute>
        <Name>uid</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>sn</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>givenName</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>ou</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>homePhone</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>telephoneNumber</Name>
      </ForeignAttribute>

      <Attribute>
        <Name>groupMembership</Name>
        <Description>A list on posix-group names this user is member of</Description>
        <Type>String</Type>
        <Backend>ObjectHandler</Backend>
        <MultiValue>true</MultiValue>
        <Validators>
          <Condition>
            <Name>ObjectWithPropertyExists</Name>
            <Param>PosixGroup</Param>
            <Param>cn</Param>
          </Condition>
        </Validators>
      </Attribute>

      <Attribute>
        <Name>uidNumber</Name>
        <Unique>true</Unique>
        <Description>An integer uniquely identifying a user in an administrative domain</Description>
        <Type>Integer</Type>
        <Mandatory>true</Mandatory>
        <Validators>
          <Condition>
            <Name>Smaller</Name>
            <Param>65500</Param>
          </Condition>
        </Validators>
        <BlockedBy>
          <Attribute value="true">autoIDs</Attribute>
        </BlockedBy>
        <DependsOn>
          <Attribute>autoIDs</Attribute>
        </DependsOn>
      </Attribute>

      <Attribute>
        <Name>gidNumber</Name>
        <Description>An integer uniquely identifying a group in an administrative domain</Description>
        <Type>Integer</Type>
        <Mandatory>true</Mandatory>
        <BlockedBy>
          <Attribute value="true">autoIDs</Attribute>
        </BlockedBy>
        <Validators>
          <Condition>
            <Name>Smaller</Name>
            <Param>65500</Param>
          </Condition>
        </Validators>
        <DependsOn>
          <Attribute>autoIDs</Attribute>
        </DependsOn>
      </Attribute>

      <Attribute>
        <Name>homeDirectory</Name>
        <Description>The absolute path to the home directory</Description>
        <Type>String</Type>
        <Mandatory>true</Mandatory>
      </Attribute>

      <Attribute>
        <Name>loginShell</Name>
        <Description>The path to the login shell</Description>
        <Type>String</Type>
		<Values populate="getShellList"/>
      </Attribute>

      <Attribute>
        <Name>gecos</Name>
        <Description>The GECOS field; the common name</Description>
        <Type>UnicodeString</Type>
        <BlockedBy>
          <Attribute value="true">autoGECOS</Attribute>
        </BlockedBy>
        <DependsOn>
          <Attribute>autoGECOS</Attribute>
        </DependsOn>
      </Attribute>
      <Attribute>
        <Name>autoGECOS</Name>
        <Default>true</Default>
        <Mandatory>true</Mandatory>
        <Backend>NULL</Backend>
        <Type>Boolean</Type>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>GenerateGecos</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
        <InFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>LoadGecosState</Name>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </InFilter>
        <DependsOn>
          <Attribute>givenName</Attribute>
          <Attribute>sn</Attribute>
          <Attribute>homePhone</Attribute>
          <Attribute>telephoneNumber</Attribute>
          <Attribute>ou</Attribute>
        </DependsOn>
      </Attribute>
      <Attribute>
        <Name>autoIDs</Name>
        <Default>true</Default>
        <Mandatory>true</Mandatory>
        <Backend>NULL</Backend>
        <Type>Boolean</Type>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>GenerateIDs</Name>
                <Param>65500</Param>
                <Param>65500</Param>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
      </Attribute>
    </Attributes>

    <Extends>
      <Value>User</Value>
    </Extends>
  </Object>
</Objects>

=== gonicus/gosa/backend/src/gosa/backend/data/objects/aclrole.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
	<Object>
		<Name>AclRole</Name>
		<DisplayName>AclRole</DisplayName>
		<Description>AclRole</Description>
		<Backend>JSON</Backend>
    <BackendParameters>
      <Backend type="AclRole" rdn="name">JSON</Backend>
    </BackendParameters>
    <Attributes>
      <Attribute>
        <Name>name</Name>
        <Description></Description>
        <Type>UnicodeString</Type>
        <Mandatory>true</Mandatory>
        <Unique>true</Unique>
      </Attribute>
      <Attribute>
        <Name>AclRoles</Name>
        <Description></Description>
        <Type>AclRole</Type>
        <BackendType>UnicodeString</BackendType>
        <MultiValue>true</MultiValue>
        <Validators>
          <Condition>
            <Name>IsAclRole</Name>
          </Condition>
        </Validators>
      </Attribute>
    </Attributes>
		<BaseObject>true</BaseObject>
    <Find>
      <Aspect>
        <Tag>AclRole</Tag>
        <Keyword>Acl</Keyword>
        <Search>name</Search>
        <Result>
          <Map>
            <Source>name</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>
	</Object>
</Objects>

=== gonicus/gosa/backend/src/gosa/backend/data/objects/group-posix.xml
<?xml version="1.0" encoding="UTF-8"?>
<Objects xmlns="http://www.gonicus.de/Objects" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gonicus.de/Objects ../object.xsd ">
  <Object>
    <Name>PosixGroup</Name>
    <Description>A posix group</Description>
    <Templates>
      <Template>group-posix.json</Template>
    </Templates>
    <DisplayName>Posix group</DisplayName>
    <BackendParameters>
      <Backend objectClasses="posixGroup">LDAP</Backend>
      <Backend memberUid="PosixUser:uid,">ObjectHandler</Backend>
    </BackendParameters>
    <Backend>LDAP</Backend>

    <Attributes>
      <ForeignAttribute>
        <Name>cn</Name>
      </ForeignAttribute>
      <ForeignAttribute>
        <Name>description</Name>
      </ForeignAttribute>
      <Attribute>
        <Name>gidNumber</Name>
        <Description>The primary group number number</Description>
        <Type>Integer</Type>
        <BlockedBy>
          <Attribute value="true">autoGid</Attribute>
        </BlockedBy>
        <DependsOn>
          <Attribute>autoGid</Attribute>
        </DependsOn>
        <Validators>
          <Condition>
            <Name>Smaller</Name>
            <Param>65500</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>memberUid</Name>
        <Description>A list of member-uids</Description>
        <Type>String</Type>
        <MultiValue>true</MultiValue>
        <Mandatory>false</Mandatory>
        <References>
          <Reference>
            <Object>PosixUser</Object>
            <Attribute>uid</Attribute>
          </Reference>
        </References>
        <Validators>
          <Condition>
            <Name>ObjectWithPropertyExists</Name>
            <Param>PosixUser</Param>
            <Param>uid</Param>
          </Condition>
        </Validators>
      </Attribute>
      <Attribute>
        <Name>autoGid</Name>
        <Default>true</Default>
        <Mandatory>true</Mandatory>
        <Backend>NULL</Backend>
        <Type>Boolean</Type>
        <Auto>true</Auto>
        <OutFilter>
          <FilterChain>
            <FilterEntry>
              <Filter>
                <Name>GenerateIDs</Name>
                <Param>65500</Param>
                <Param>65500</Param>
              </Filter>
            </FilterEntry>
          </FilterChain>
        </OutFilter>
      </Attribute>
    </Attributes>
    <BaseObject>false</BaseObject>
    <Extends>
      <Value>GroupOfNames</Value>
    </Extends>

    <Find>
      <Aspect>
        <Tag>PosixGroup</Tag>
        <Keyword>Group</Keyword>
        <Keyword>Member</Keyword>
        <Keyword>Membership</Keyword>
        <Search>cn</Search>
        <Search>description</Search>
        <Resolve type="User" filter="uid">memberUid</Resolve>
        <Result>
          <Map>
            <Source>cn</Source>
            <Destination>title</Destination>
          </Map>
        </Result>
      </Aspect>
    </Find>

  </Object>
</Objects>
